-
  name: 'Jenkins Server Setup with configurtion and plugins'
  hosts: mygroup
  tasks:
  -
    name: 'Install Java'
    become: true
    apt:
      name: '{{ packages }}'
      state: present
      update_cache: yes
    vars:
      packages:
        - python3-boto3
        - python3-botocore
